language: objective-c

branches:
    only:
        - master
        - dev

notifications:
    email: false
    slack:
        secure: OX9uWE+VLBZN+zfN/ov8jq6lElmJxLcw+ME//ziAlKdDGs7qJbtlnJv9qCHO5e0BCf9Qt3UrKicK4ppJ3B5F7DL+7EKAF0z2DRxLqz/MRWgIqQoC/9IUEfGoc/Ff9XoMoIvBSH1gcR7Y6zcUgJluudQBGZGbGx2UC42GKGBZnYY=
        on_success: change
        on_failure: always

before_install:
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

install:
    - pod lib lint --quick

script:
    - set -o pipefail && xcodebuild test -workspace Example/CocoaBloc-Camera.xcworkspace -scheme CocoaBloc-Camera-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -tc
