language: objective-c

branches:
    only:
        - master
        - dev

notifications:
    email: false
    slack:
        secure: OX9uWE+VLBZN+zfN/ov8jq6lElmJxLcw+ME//ziAlKdDGs7qJbtlnJv9qCHO5e0BCf9Qt3UrKicK4ppJ3B5F7DL+7EKAF0z2DRxLqz/MRWgIqQoC/9IUEfGoc/Ff9XoMoIvBSH1gcR7Y6zcUgJluudQBGZGbGx2UC42GKGBZnYY=
        on_success: change
        on_failure: always

before_install:
    - brew update
    - brew outdated xctool || brew upgrade xctool

install:
    - pod lib lint --quick

script:
    - xctool test -freshSimulator -test-sdk iphonesimulator -workspace Example/CocoaBloc-Camera.xcworkspace -scheme CocoaBloc-Camera-Example -reporter plain
