language: objective-c

notifications:
    email: false
    slack:
        rooms:
            - secure: "ijz0tVYV6ecUKOVeNpikfBmaU/Dj1rvBXbvF8iFh/0UCEPsoY3BEm4KjubizRxt9Sie25b+38NU7ICoLOZTMfAqm0srVt5ys3jwdJA2D/17A29g7B2Fjke+oqq2FQyb1Fb+Mpg9jQqQg2R1kywYc72CbczWdR7bCsF6Im1dF+kg="
        on_success: change
        on_failure: always

before_install:
    - gem install cocoapods
    - brew update
    - brew outdated xctool || brew upgrade xctool

install:
    - pod lib lint --quick

script:
    - xctool test -freshSimulator -test-sdk iphonesimulator -workspace Example/CocoaBloc-Camera.xcworkspace -scheme CocoaBloc-Camera-Example -reporter pretty
